INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Комедия', null);
INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Драма', null);
INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Мультфильм', null);
INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Триллер', null);
INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Документальный', null);
INSERT INTO PUBLIC.GENRE (NAME, DESCRIPTION) VALUES ('Боевик', null);

INSERT INTO PUBLIC.MOTION_PICTURE_ASSOCIATION (NAME, DESCRIPTION) VALUES ('G', 'GGG');
INSERT INTO PUBLIC.MOTION_PICTURE_ASSOCIATION (NAME, DESCRIPTION) VALUES ('PG', 'GGG');
INSERT INTO PUBLIC.MOTION_PICTURE_ASSOCIATION (NAME, DESCRIPTION) VALUES ('PG-13', 'GGG');
INSERT INTO PUBLIC.MOTION_PICTURE_ASSOCIATION (NAME, DESCRIPTION) VALUES ('R', 'GGG');
INSERT INTO PUBLIC.MOTION_PICTURE_ASSOCIATION (NAME, DESCRIPTION) VALUES ('NC-17', 'GGG');